name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install langchain langchain-openai langchain-chroma langchain-community openai chromadb PyPDF2 pypdf
    - name: Run the notebook
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python notebook_rag.py
